<?php namespace Eternity2\Module\Zuul;

class Event{
	const AUTOLOGIN = __CLASS__.'AUTOLOGIN';
	const LOGIN = __CLASS__.'LOGIN';
	const LOGOUT = __CLASS__.'LOGOUT';
	const LOGIN_ERROR_USER_NOT_FOUND = __CLASS__.'LOGIN_ERROR_USER_NOT_FOUND';
	const LOGIN_ERROR_WRONG_PASSWORD = __CLASS__.'LOGIN_ERROR_WRONG_PASSWORD';
	const LOGIN_ERROR_WRONG_PERMISSION = __CLASS__.'LOGIN_ERROR_WRONG_PERMISSION';
}