<?php namespace Eternity2\Module\Zuul;

class Event{
	const EVENT_LOGIN = __CLASS__.'EVENT_LOGIN';
	const EVENT_LOGOUT = __CLASS__.'EVENT_LOGOUT';
	const EVENT_LOGIN_ERROR_USER_NOT_FOUND = __CLASS__.'EVENT_LOGIN_ERROR_USER_NOT_FOUND';
	const EVENT_LOGIN_ERROR_WRONG_PASSWORD = __CLASS__.'EVENT_LOGIN_ERROR_WRONG_PASSWORD';
	const EVENT_LOGIN_ERROR_WRONG_PERMISSION = __CLASS__.'EVENT_LOGIN_ERROR_WRONG_PERMISSION';
}